(IO-1) Immutable complex command & commands code clean-up
iis-powp-2024/powp_jobs2d_projects pull request #44
Opened 2024-05-23 11:07 UTC by BartoszChadrys

2024-05-24 09:32 UTC, kowallus requested changes
There are some minor issues, to fix and cleanup.
Please take care also of CommandManager class. There is a long anonymous ICompoundCommand class which can be replaced with 1 line ImmutableCommand. 
Check also it there are other usages of ICompundCommand interface,

2024-05-24 09:32 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CompoundCommand.java
> +public final class CompoundCommand implements ICompoundCommand {
Change name to ImmutableCompoundCommand.

2024-05-24 09:32 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CompoundCommand.java
> +        this.commands = new ArrayList<>(commands);
References to commands in the _commands_ list exist inside the created CompoundCommand instance and outside (because they were passed in the parameter). There is no guarantee that they won't be modified outside. 
To ensure immutability you should make copy (see your code in getCommands). Try to avoid code duplication and object redundancy.

2024-05-24 09:32 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverUsageDecorator.java
From where did you get this class? I do not see it here:
https://github.com/iis-powp-2024/powp_jobs2d_projects/tree/dev-io-1/src/main/java/edu/kis/powp/jobs2d/drivers

Please resolve this issue.

2024-06-09 11:39 UTC, olekgolus11 commented on src/main/java/edu/kis/powp/jobs2d/command/CompoundCommand.java
> +        this.commands = new ArrayList<>(commands);
We have now extracted the copying to new private method which is reused in both constructor and `getCommands()`

2024-06-10 08:45 UTC, kowallus approved these changes

2024-06-10 08:54 UTC, merged