Mode for adjusting the draw panel using a mouse
iis-powp-2024/powp_jobs2d_projects pull request #49
Opened 2024-05-30 14:15 UTC by JakGin

Feature presentation:
https://github.com/iis-powp-2024/powp_jobs2d_projects/assets/84508832/837b1202-3a17-47e8-9606-5689fbc83b58

2024-05-31 06:49 UTC, kowallus requested changes
I have tested the solution and it works quite nice. Please consider the following changes:

1. Major - the adjusted panel is applied to already drawn lines only. The next operations on a driver are executed without transformation. E.g., I have run 'Figure Joe 1' script several times:
![image](https://github.com/iis-powp-2024/powp_jobs2d_projects/assets/6030543/c0eb6f5d-7aff-40c2-b130-3aa7668d15c6) and it is always drawn with the same size and position in the middle.

2. Minor - after zooming out there is a loss in precision of the lines and some lines even collapse into a single point, however, I understand that keeping original coordinates might be difficult.

2024-05-31 06:49 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/LineDriverAdapter.java
> +        } catch (CloneNotSupportedException ignored) {}
The solution would be better if LinesRecorder dependency could be avoided. Maybe, the decorator approach is possible by providing a 'line' clone getter in LineDriverAdapter.

2024-06-14 10:01 UTC, JakGin commented
Major and Minor problem from above fixed. 
Short presentation how it works: https://github.com/iis-powp-2024/powp_jobs2d_projects/assets/84508832/b65942f1-c42f-43df-9508-88d8051957ae
By introducing decorator that wraps LineDriverAdapter it's hard to integrate it to every test. It would require wrapping LineDriverAdapter with the new decorator everywhere. It also not possible to just wrap the currentDriver since the driver might not be an instance of LineDriverAdapter but some other decorator perhaps. It would be perfect to wrap the Job2dDriver instead, but the new decorator needs the lineClone() that only LineDriverAdapter has.

2024-06-18 15:35 UTC, kowallus approved these changes
In some places, more OCP would be easily possible. 4.5 project final

2024-06-18 15:35 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/LineDriverAdapterRecordingDecorator.java
> +    public void setPosition(int i, int i1) {
Bad param names

2024-06-18 15:35 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/LineDriverAdapterRecordingDecorator.java
> +            linesTransformationExecutor.execute(new ScaleTransformation(currentZoom));
Not OCP. Handling another transformation requires modification here.

2024-06-18 15:35 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/WorkspaceTransformationFeature.java
> +    private static DrawPanelMouseZoomFeature drawPanelMouseZoomFeature;
This part could also be more OCP.

2024-06-18 15:35 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/LineDriverAdapterRecordingDecorator.java
> +            linesTransformationExecutor.execute(new ScaleTransformation(currentZoom));
Creating a new instance of ScaleTransofrmation every time is a waste of resources.

2024-06-18 15:35 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/transformations/LinesTransformationExecutor.java
> +            if (transformation instanceof ScaleTransformation) {
Not Object-Oriented way. Avoiding instanceof is probably possible (maybe Strategy or Visitor?)

2024-06-18 15:36 UTC, merged