Implemented observer pattern for driver change
iis-powp-2024/powp_jobs2d_projects pull request #7
Opened 2024-04-06 11:07 UTC by milczarekmat

2024-04-08 07:06 UTC, kowallus requested changes
Great! Please fix the name of the observer class to reflect its purpose.

2024-04-08 07:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/gui/DriverChangeObserver.java
> +public class DriverChangeObserver implements Subscriber {
All DriverManager observers will be driver change observers. The name of observer should also describe its activity. Please rename.

2024-04-11 07:22 UTC, kowallus requested changes
Fix name (java convention) and resolve conflicts (merge changes from other PR-s).

2024-04-11 07:22 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/gui/updateDriverInfoObserver.java
> +public class updateDriverInfoObserver implements Subscriber {
Class name should start from UpperCase!

2024-04-11 08:27 UTC, Yibux commented on src/main/java/edu/kis/powp/jobs2d/drivers/gui/updateDriverInfoObserver.java
> +public class updateDriverInfoObserver implements Subscriber {
Class name renamed

2024-04-11 08:58 UTC, Yibux approved these changes

2024-04-11 09:00 UTC, Yibux approved these changes

2024-04-11 09:14 UTC, kowallus approved these changes

2024-04-11 09:15 UTC, merged