Apply transformation after choosing a transformation driver
iis-powp-2024/powp_jobs2d_projects pull request #73
Opened 2024-08-05 04:41 UTC by MateuszMagd

Made by Martyna Kaszczyk and Mateusz Magdziński

2024-09-09 09:06 UTC, kowallus requested changes
Almost ok. One important issue to fix.

Secondary issue: Your solution does not work with some driver configurations, e.g., composite drivers: "Special Line with Vertical Flip and Detailed Logger". You should be aware of such disabilities. Fixing is not obligatory.

2024-09-09 09:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/transformations/changedriver/ApplyTransformationToNewDriver.java
> +        command.execute(DriverFeature.getDriverManager().getCurrentDriver());
My main concern regarding this solution is that it uses commands manager for refreshing/restarting the transformation. It seems totally unnecessary, and makes harder to use commands manager. 
Please remove any CommandManager usages in your solution.

2024-09-09 09:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/transformations/changedriver/WrapDriverWithRecordingDecoratorObserverWhileChaningDriver.java
> +public class WrapDriverWithRecordingDecoratorObserverWhileChaningDriver implements Subscriber {
...ChaningDriver -> ....(Changing/Chaining?)Driver

2024-09-10 19:24 UTC, MateuszMagd commented
I am not sure if this solution is okey but this use in ApplyTransformationToNewDriver is essenstial by my perspective

2024-09-11 07:46 UTC, kowallus requested changes
Apply solution without messing up CommandManager.

2024-09-11 07:46 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/transformations/changedriver/ApplyTransformationToNewDriver.java
> +        CommandsFeature.getCommandManager().getCurrentCommand().execute(DriverFeature.getDriverManager().getCurrentDriver());
No. You still use CommandManager. Executing commands do not require commands manager. You can simply do:
RecordCommandsForTransformation.getRecordedCommand().execute(DriverFeature.getDriverManager().getCurrentDriver())).

2024-09-14 19:36 UTC, kowallus reviewed
Thank you. Grade 3 for the project.

2024-09-14 19:36 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/transformations/changedriver/ApplyTransformationToNewDriver.java
> +        RecordCommandsForTransformation.getRecordedCommand().execute(DriverFeature.getDriverManager().getCurrentDriver());
You have forgotten to clean up imports (import edu.kis.powp.jobs2d.command.manager.ICommandManager).

For a cleaner code, this command should be divided into at least 3 lines.

2025-06-28 18:45 UTC, closed without merging