History
iis-powp-2024/powp_jobs2d_projects pull request #74
Opened 2024-08-06 20:46 UTC by lilskywalkr

2024-08-07 11:58 UTC, kowallus requested changes
See my remarks

2024-08-07 11:58 UTC, kowallus commented on .idea/.gitignore
unnecessary .idea folder files. Remove!

2024-08-07 11:58 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/HistoryFeatureObserver.java
> +    public List<DriverCommand> commandList = new ArrayList<>();
It would be best if the "history" would keep the details about timeline (basic chronology).

2024-08-07 11:58 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/HistoryFeatureObserver.java
> +        System.out.println("HistoryFeatureObserver: " + commandManager.getCurrentCommandString());
Using System.out is not prefered way of the interaction in this app. You should use log or GUI.

2024-08-07 11:58 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +        application.addTest("Add recorded command to history", new SelectHistoryAdditionRecordingOptionListener());
Not necessary. Application should add all commands "Loaded" to command manager. You have no need to support "recorded command" in a special way. Clicking "Load recorded command" triggers setCurrentCommand event. You should implement observer that reacts to this event and loads the current command to the history.

2024-08-07 11:58 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/macro/RecordingManager.java
> +public class RecordingManager {
???

2024-08-07 11:58 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/HistoryFeatureObserver.java
> +        this.currentCommand = commandManager.getCurrentCommand();
In my opinion, update should add current command to the History.

2024-08-11 17:58 UTC, lilskywalkr commented on src/main/java/edu/kis/powp/jobs2d/command/gui/HistoryFeatureObserver.java
> +    public List<DriverCommand> commandList = new ArrayList<>();
The timeline of the recorded commands are kept in the command's name when adding one to the history in SelectHistoryAdditionRecordingOptionListener 

![obraz_2024-08-11_195752416](https://github.com/user-attachments/assets/629be7eb-b064-4e20-9ce6-3fab7d0f5ad5)

2024-08-11 21:42 UTC, lilskywalkr commented on src/main/java/edu/kis/powp/jobs2d/macro/RecordingManager.java
> +public class RecordingManager {
Deleted this redundant class

2024-08-11 21:42 UTC, lilskywalkr commented on src/main/java/edu/kis/powp/jobs2d/command/gui/HistoryFeatureObserver.java
> +        System.out.println("HistoryFeatureObserver: " + commandManager.getCurrentCommandString());
The logs are now displayed on the GUI

2024-08-11 21:44 UTC, lilskywalkr commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +        application.addTest("Add recorded command to history", new SelectHistoryAdditionRecordingOptionListener());
Command addition to the history is now synchronized with "Load recorded command"

2024-08-11 22:02 UTC, lilskywalkr commented on src/main/java/edu/kis/powp/jobs2d/command/gui/HistoryFeatureObserver.java
> +        this.currentCommand = commandManager.getCurrentCommand();
update now adds commands to the history list

2024-08-11 22:13 UTC, lilskywalkr commented on .idea/.gitignore
Folder deleted

2024-08-15 15:29 UTC, kowallus reviewed
OK. Thank you.

2024-09-15 12:06 UTC, closed without merging